routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier
    
routingProduit:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix: /
    
routingCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
    prefix: /