panier:
    path:     /
    defaults: { _controller: EcommerceBundle:Panier:panier }
    
ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouter }
    
suprimer:
    path:     /suprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:suprimer }
    
livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }
  
livraisonAdresseSuppression:
    path:     /livraison/adresse/supression/{id}
    defaults: { _controller: EcommerceBundle:Panier:adresseSuppresion }
    