<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function byFacture($utilizateur)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.utilizateur = :utilizateur')
                ->andWhere('u.valider = 1')
                ->andWhere('u.reference != 0')
                ->orderBy('u.id')
                ->setParameter('utilizateur', $utilizateur);
                
        return $qb->getQuery()->getResult();
    }
}
